name: Build Windows Executable

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Using 3.11 to avoid Python 3.10.0 PyInstaller bug

      - name: Install Python Dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build Application
        run: python build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GravityBlu-Windows
          path: dist/GravityBlu/
